apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vmsingle
  namespace: monitoring-system
spec:
  retentionPeriod: "4d"
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
---

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmservicescrape
  namespace: monitoring-system
spec:
  namespaceSelector:
    matchNames:
      - application
  selector:
    matchLabels:
      service: django
  endpoints:
    - port: metrics
      path: /api/metrics
---

apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: monitoring-system
spec:
  serviceScrapeNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: monitoring-system

  serviceScrapeSelector:
    matchLabels: {}

  replicaCount: 1

  scrapeInterval: 15s

  remoteWrite:
    - url: "http://vmauth-hamamooz-vmauth.monitoring-system.svc:8427/api/v1/write"
      basicAuth:
        username:
          name: vmuser-vmagent-writer
          key: username
        password:
          name: umuser-vmagent-writer
          key: password
