apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring-system
stringData:
  alertmanager.yaml: |
    route:
      receiver: 'telegram'
    receivers:
      - name: 'telegram'
        telegram_configs:
          - bot_token: '8518520444:AAFCsNPFhbTpFn5TtTQXWVjWpOkZ5ic-3Qw'
            chat_id: 1669232165
            message: 'hello alert'
