apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring-system
stringData:
  alertmanager.yaml: |
    route:
      receiver: 'webhook'
      repeat_interval: 1s
    receivers:
      - name: 'webhook'
        webhook_configs:
          - url: 'http://webhook-service.monitoring-system.svc.cluster.local:8080/webhookapp/alerts'
            send_resolved: true
