apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: monitoring-system
spec:
  replicaCount: 1
  datasource:
    url: "http://vmsingle-vmsingle.monitoring-system.svc:8429"
  notifiers:
    - url: "http://vmalertmanager-vmalertmanager.monitoring-system.svc:9093"
  remoteWrite:
    url: "http://vmsingle-vmsingle.monitoring-system.svc:8429"
  evaluationInterval: "30s"
  ruleSelector:
    matchLabels:
      app: vmrule
