apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata:
  name: backup-rule
  namespace: monitoring-system
  labels:
    app: vmrule
spec:
  groups:
    - name: test-alert
      rules:
        - alert: BackupJobsCountTooHigh
          expr: sum(hamamooz_backup_jobs_total) > 10
          for: 20s
